language: java

deploy:
    provider: script
    script: "mvn clean install"

addons:
    sonarcloud:
        organization: "viswesvar" #test
        token:
            secure: $SONAR_TOKEN

script:
    - sonar-scanner
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=viswesvar@github
