language: java
dist: trusti


addons:
    sonarcloud:
        organization: "viswesvar" #test
        token:
            secure: $SONAR_TOKEN

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
cache:
  directories:
    - '$HOME/.sonar/cache'
    
