language: java

deploy:
    provider: script
    script: "mvn clean install"

addons:
    sonarcloud:
        organization: "SONAR_TOKEN" #test
        token:
            secure: "efdd1837d2aade79b0b894614c7645dd0e1e9d5a"

script:
    - sonar-scanner
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=viswesvar@github
