language: java

deploy:
    provider: script
    script: "mvn clean install"

addons:
    sonarcloud:
        organization: "Viswesvar" #test
        token:
            secure: efdd1837d2aade79b0b894614c7645dd0e1e9d5a

script:
    - sonar-scanner