language: java

deploy:
    provider: script
    script: "mvn clean install"

addons:
    sonarcloud:
        oragnization: "Viswesvar Sekar" #test
        token:
            secure: 75a3600d744de87a9d468b2d61755ce1819ed1f0

script:
    - sonnar-scanner